name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  call-template:
    uses: gad-adel/Recolnat-Template/.github/workflows/github-ci-template.yml@main
    with:
      project_ci: Recolnat-explorer
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      HARBOR_REGISTRY_USER: ${{secrets.HARBOR_REGISTRY_USER }}
      HARBOR_REGISTRY_PASSWORD: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}
    permissions:
      contents: read
