INSERT INTO institution(code,name, mandatory_description, optional_description, logo_url, partner_type, created_by,created_at) VALUES
									  ('MNHN','Muséum National d''Histoire Naturelle', '', NULL, NULL, 'PARTNER', 'script', now())
 									 ,('CJBN','Conservatoire et jardins botaniques de Nancy', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('SNSNMC','Société nationale des sciences naturelles et mathématiques de Cherbourg(CHE)', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('CLF','Université de Clermont-Ferrand', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('CBNA','Conservatoire botanique national Alpin', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('JUN','Herbier de Saint-Junien', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('RABAT','Rabat Maroc, Université', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('FEN','Comité du patrimoine manosquin', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNAIX','Muséum d''Histoire Naturelle d''Aix', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UM','Université de Montpellier', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('ANDUZE','La bambouseraie d''Anduze', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('ANVL','Association des Naturalistes de la Vallée du Loing', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('BIBLIMO','Université de Limoges', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('AUT','Muséum d''Histoire Naturelle d''Autun', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('CIRAD-IEMVT','CIRAD', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('RENTEST','Université de Rennes', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('CBPF','Conservatoire Botanique Pierre Fabre', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('BESA','Muséum d''Histoire Naturelle de Besançon', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('VIL','Herbier de la Ville de Verrières-le-Buisson', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('ANG','Muséum d''Angers', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('CBNSA','Conservatoire Botanique National Sud-Atlantique', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('LYJB','Jardin botanique de Lyon', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MPU','', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('AUR','Muséum des Volcans', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MENDE','Musée du Gévaudan', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('AV','Muséum d''Avignon', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('STR','Université de Strasbourg', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('SLA','Société des Lettres de l''Aveyron', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UB','Université de Bourgogne', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('NIM','Muséum d''histoire naturelle de Nîmes', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MARS','Université d''Aix-Marseille', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('ML','Musée des Sciences (Laval)', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('PUY','Musée Crozatier', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UBO','Université de Bretagne Occidentale, Brest', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('PNC','Parc National des Cévennes', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('BBF','Conservatoire botanique national des Pyrénées et de Midi-Pyrénées', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MAN','Muséum-Aquarium de Nancy', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNTOULOUSE','Muséum d''Histoire Naturelle de Toulouse', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('BOUM','Muséum d''histoire naturelle de Bourges', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MMSA','Musée municipal de Semur-en-Auxois', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNLM','Muséum d''histoire naturelle du Mans', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('TL','Université de Toulouse', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('REN','Université de Rennes 1', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UCBL','Université Claude Bernard Lyon 1', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MTL','Musée Toulouse-Lautrec', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UBDX','Université de Bordeaux', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('CBUM','Université de Montréal Biodiversity Centre', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UCB','Université Claude Bernard - Lyon I', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('EIDM','EID Méditerranée', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('EPF','Musée de l''Espace Pierre Folles', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('BAIL','Conservatoire Botanique National de Bailleul', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('AUX','Muséum d''histoire naturelle d''Auxerre', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNLILLE','Muséum d''histoire naturelle de Lille', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('ULFST','Université de Lille – Faculté des Sciences et Technologies', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('CHML','Centre Historique Minier de Lewarde', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('METZ','Musée de Metz Métropole : La Cour d''Or', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('LIP','Faculté des Sciences Pharmaceutiques et Biologiques de L''Université de Lille 2', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('GRM','Muséum d''histoire naturelle de Grenoble', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNT','Muséum d''Histoire Naturelle de Toulon', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('PHUAN','Phu AN Bambou village-Viet Nam Université Nationale de HCMV', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('VTA','INRAE Villa Thuret', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNO','Muséum d''Orléans pour la Biodiversité et l''Environnement', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UPSUD','Université Paris Sud', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('TLS','Université Paul Sabatier - Toulouse', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('INRA','Institut national de la recherche agronomique', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHLCLF','Muséum Henri-Lecoq', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MJSD','Muséum Jardin des Sciences de Dijon', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MC','Musée Cuvier de Montbéliard', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNN','Muséum d''histoire naturelle de Nantes', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNO','Muséum d''histoire naturelle d''Orléans', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MGP','Musée de la Préhistoire Le Grand Pressigny', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UCO','Université Catholique de l''Ouest - Angers', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('PNRL','Parc Naturel Régional du Luberon', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MR','Muséum d''histoire naturelle Requien d''Avignon', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('GR','Université Grenoble Alpes', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNVBM','Muséum d''histoire naturelle Victor Brun Montauban', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UN','Université de Nantes', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MSSL','Musée de Savigné-sur-Lathan', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNLR','Muséum d''histoire naturelle de La Rochelle', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('NICE','Muséum d''Histoire Naturelle de Nice', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MHNM','Muséum d''histoire naturelle de Marseille', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('M0841','Musée d''Histoire naturelle de Niort', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('IRD','Institut de recherche pour le développement', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UP','Université de Poitiers', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('UL','Université de Lorraine', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('SU','Sorbonne Université', '', NULL, NULL, 'PARTNER', 'script', now())
                                     ,('MAJD','Musée de l''Avallonnais Jean Desprès', '', NULL, NULL, 'PARTNER', 'script', now());
